version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: grafana_mosquitto
    ports:
      - "1883:1883"
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - ./mosquitto-no-auth.conf:/mosquitto-no-auth.conf

  postgres:
    image: postgres:13
    container_name: grafana_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lindu_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  ingester:
    build: 
      context: ./ingester
      dockerfile: Dockerfile
    container_name: grafana_ingester
    depends_on:
      - mosquitto
      - postgres
    environment:
      MQTT_HOST: mosquitto
      DB_HOST: postgres
    ports:
      - "5001:5000"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/seismic.json
    depends_on:
      - postgres
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
